using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace euler_oiler
{
    public class EulerSolver
    {
        /* 
            PROBLEM ONE
            If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
            The sum of these multiples is 23.

            Find the sum of all the multiples of 3 or 5 below 1000.
        */
        public string SolveProblemOne()
        {
            int sumTotal = 0;

            for (int i = 0; i <1000; i++)
            {
                if (i % 3 == 0 || i % 5 == 0)
                {
                    sumTotal += i;
                }
            }

            return sumTotal.ToString();
        }

        /*
            Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
        
            By starting with 1 and 2, the first 10 terms will be:

            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

            By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
            find the sum of the even-valued terms.
        */
        public string SolveProblemTwo()
        {
            int total = 0;
            int currentFibNum = 1;
            int previousFibNum = 0;

            while (currentFibNum < 4000000) {
                if (currentFibNum % 2 == 0)
                {
                    total += currentFibNum;
                }

                var oldPrevValue = previousFibNum;
                previousFibNum = currentFibNum;
                currentFibNum += oldPrevValue;
            }

            return total.ToString();
        }

        /*
            The prime factors of 13195 are 5, 7, 13 and 29.

            What is the largest prime factor of the number 600851475143 ?
        */
        public string SolveProblemThree()
        {
            long result = 0; 
            long currentDividend = 600851475143;

            result = MathHelper.GetHighestPrimeFactor(currentDividend);

            return result.ToString();
        }
    }
}
